# Generated by Django 4.2.11 on 2024-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_site', '0002_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(default='Wagon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Nairobi, Ngong', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=100),
        ),
    ]
