# Generated by Django 4.2.11 on 2024-05-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_site', '0003_car_body_type_car_fuel_type_car_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AddField(
            model_name='car',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('suv', 'Suv'), ('van', 'Van'), ('truck', 'Truck'), ('wagon', 'Wagon'), ('convertible', 'Convertible'), ('minivan', 'Minivan'), ('pickup', 'Pickup')], default='sedan', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=100),
        ),
    ]
