# Generated by Django 4.2.11 on 2024-05-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
