# Generated by Django 4.2.11 on 2024-06-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_site', '0004_remove_car_status_car_sold_alter_car_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('SUV', 'Suv'), ('Van', 'Van'), ('Pickup', 'Pickup'), ('Double Cab', 'Double Cab'), ('Wagon', 'Wagon'), ('Convertible', 'Convertible'), ('Minivan', 'Minivan')], default='Sedan', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], default='Petrol', max_length=100),
        ),
    ]
